# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTextEdit, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.setEnabled(True)
        Widget.resize(800, 600)
        self.encrypt_btn = QPushButton(Widget)
        self.encrypt_btn.setObjectName(u"encrypt_btn")
        self.encrypt_btn.setGeometry(QRect(370, 170, 61, 32))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 10, 321, 31))
        font = QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.raw_text = QTextEdit(Widget)
        self.raw_text.setObjectName(u"raw_text")
        self.raw_text.setGeometry(QRect(20, 120, 341, 201))
        self.ecrypted_text = QTextEdit(Widget)
        self.ecrypted_text.setObjectName(u"ecrypted_text")
        self.ecrypted_text.setGeometry(QRect(440, 120, 341, 201))
        self.decryption_btn = QPushButton(Widget)
        self.decryption_btn.setObjectName(u"decryption_btn")
        self.decryption_btn.setGeometry(QRect(370, 240, 61, 32))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 330, 58, 16))
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(450, 330, 121, 16))
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(280, 40, 231, 31))
        font1 = QFont()
        font1.setPointSize(18)
        self.label_4.setFont(font1)
        self.listen_port = QLineEdit(Widget)
        self.listen_port.setObjectName(u"listen_port")
        self.listen_port.setGeometry(QRect(20, 410, 111, 31))
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 390, 71, 16))
        self.listen_btn = QPushButton(Widget)
        self.listen_btn.setObjectName(u"listen_btn")
        self.listen_btn.setGeometry(QRect(20, 440, 111, 32))
        self.local_server_listening = QLabel(Widget)
        self.local_server_listening.setObjectName(u"local_server_listening")
        self.local_server_listening.setEnabled(False)
        self.local_server_listening.setGeometry(QRect(20, 370, 171, 16))
        self.remote_ip = QLineEdit(Widget)
        self.remote_ip.setObjectName(u"remote_ip")
        self.remote_ip.setGeometry(QRect(150, 410, 111, 31))
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 390, 71, 16))
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 450, 91, 16))
        self.remote_port = QLineEdit(Widget)
        self.remote_port.setObjectName(u"remote_port")
        self.remote_port.setGeometry(QRect(150, 470, 111, 31))
        self.connect_btn = QPushButton(Widget)
        self.connect_btn.setObjectName(u"connect_btn")
        self.connect_btn.setGeometry(QRect(150, 510, 111, 32))
        self.send_btn = QPushButton(Widget)
        self.send_btn.setObjectName(u"send_btn")
        self.send_btn.setEnabled(False)
        self.send_btn.setGeometry(QRect(450, 510, 111, 32))
        self.username_lbl = QLabel(Widget)
        self.username_lbl.setObjectName(u"username_lbl")
        self.username_lbl.setEnabled(False)
        self.username_lbl.setGeometry(QRect(450, 390, 71, 16))
        self.username = QLineEdit(Widget)
        self.username.setObjectName(u"username")
        self.username.setEnabled(False)
        self.username.setGeometry(QRect(450, 410, 111, 31))
        self.password = QLineEdit(Widget)
        self.password.setObjectName(u"password")
        self.password.setEnabled(False)
        self.password.setGeometry(QRect(450, 470, 111, 31))
        self.password.setInputMethodHints(Qt.InputMethodHint.ImhHiddenText|Qt.InputMethodHint.ImhNoAutoUppercase|Qt.InputMethodHint.ImhNoPredictiveText|Qt.InputMethodHint.ImhSensitiveData)
        self.password.setEchoMode(QLineEdit.EchoMode.Password)
        self.password_lbl = QLabel(Widget)
        self.password_lbl.setObjectName(u"password_lbl")
        self.password_lbl.setEnabled(False)
        self.password_lbl.setGeometry(QRect(450, 450, 91, 16))
        self.remote_server_connected = QLabel(Widget)
        self.remote_server_connected.setObjectName(u"remote_server_connected")
        self.remote_server_connected.setEnabled(False)
        self.remote_server_connected.setGeometry(QRect(150, 550, 211, 16))
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(370, 150, 58, 16))
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(370, 220, 58, 16))
        self.send_status_lbl = QLabel(Widget)
        self.send_status_lbl.setObjectName(u"send_status_lbl")
        self.send_status_lbl.setEnabled(False)
        self.send_status_lbl.setGeometry(QRect(450, 370, 211, 16))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.encrypt_btn.setText(QCoreApplication.translate("Widget", u">>", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Security and encryption", None))
        self.decryption_btn.setText(QCoreApplication.translate("Widget", u"<<", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Raw text", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Encrypted text", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"AES 256 - PKCS7(128) - CBC", None))
        self.listen_port.setText(QCoreApplication.translate("Widget", u"8080", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Listen Port", None))
        self.listen_btn.setText(QCoreApplication.translate("Widget", u"Listen", None))
        self.local_server_listening.setText(QCoreApplication.translate("Widget", u"Listening: False", None))
        self.remote_ip.setText(QCoreApplication.translate("Widget", u"127.0.0.1", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Remote IP", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Remote Port", None))
        self.remote_port.setText(QCoreApplication.translate("Widget", u"8080", None))
        self.connect_btn.setText(QCoreApplication.translate("Widget", u"Connect", None))
        self.send_btn.setText(QCoreApplication.translate("Widget", u"Send", None))
        self.username_lbl.setText(QCoreApplication.translate("Widget", u"Usuario", None))
        self.password_lbl.setText(QCoreApplication.translate("Widget", u"Password", None))
        self.remote_server_connected.setText(QCoreApplication.translate("Widget", u"Connected: False", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Encrypt", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Decrypt", None))
        self.send_status_lbl.setText(QCoreApplication.translate("Widget", u"...", None))
    # retranslateUi

